name: Backup Database

on:
  schedule:
    - cron: '0 2 * * *' # Planifier pour s'exécuter tous les jours à 2h du matin
  workflow_dispatch: # Permet d'exécuter manuellement le workflow

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run backup script
      run: ./scripts/backup.sh
